### PR TITLE
Add arrow navigation for command history

### PR DESCRIPTION
**Pull request by bachletuankhai**
This mimics the behavior of a terminal: You can use arrow keys ⬆️ and ⬇️ to navigate to past commands. The user can use this feature when the command box is focused (the behavior is handled in [`CommandBox.java`](https://github.com/bachletuankhai/tp/blob/branch-HistoryArrowNav/src/main/java/seedu/address/ui/CommandBox.java) only).

### CODE REVIEW

**Comment by bachletuankhai** [comment]
I will add more test later

**Comment by bachletuankhai** [comment]
I guess we can skip the codecov check for now. It does not affect the overall coverage (-0.65%)

**Comment by dhlee03** [comment]
Can you add missing testcases for the logic manager?

**Comment by dhlee03** [comment]
I also think it is difficult to test UI.

**Comment by bachletuankhai** [comment]
> Can you add missing testcases for the logic manager?

It is 1 line missing 🤔. I only add a getter for history. So no need?

**Comment by bachletuankhai** [comment]
There are no test cases for other getters in LogicManager too

**Comment by dhlee03** [comment]
LGTM.

**Review by dhlee03 — APPROVED** [review]
LGTM.

**Pull request merged**
